# Generated by Django 4.1.4 on 2022-12-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="картинка"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=128, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="week_day",
            field=models.CharField(
                choices=[
                    ("Monday", "понедельник"),
                    ("Tuesday", "вторник"),
                    ("Wednesday", "среда"),
                    ("Thursday", "четверг"),
                    ("Friday", "пятница"),
                    ("Saturday", "суббота"),
                    ("Sunday", "воскресенье"),
                ],
                max_length=15,
                unique=True,
                verbose_name="день недели",
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table="main_products",
        ),
    ]
